version: '3'
services:
    server:
        container_name: server
        restart: always
        build: ./server
        ports:
            - '8000:8000'
        # depends_on:
        #     - mongo
    # mongo:
    #     container_name: mongo
    #     image: mongo
    #     ports:
    #         - '27017:27017'
